#!/usr/bin/env node
// Build the embedded deposit app (EDAA) from its readable source file.
//
// Source of truth : src-frontend/deposit-app.html
// Build target    : src-frontend/deposit-app-blob.js  (fully generated —
//                   `window.__EDAA_B64__ = \`<base64>\``, shipped lazily as
//                   chunk-deposit.js by scripts/build-frontend.mjs)
//
// Modes:
//   node scripts/build-edaa.mjs             encode source -> rewrite the blob file
//   node scripts/build-edaa.mjs --check     verify the blob matches the source (no writes)
//   node scripts/build-edaa.mjs --extract   decode FROM the blob back into the source file
//
// The runtime decoder is decodeBase64Utf8 (atob -> TextDecoder utf-8), i.e. the
// base64 payload is the raw UTF-8 bytes of the HTML document. This script works
// on raw bytes (Buffer <-> base64) so the round trip is byte-exact.
//
// After editing deposit-app.html run BOTH steps (or `npm run build:edaa` which
// chains them): this script, then build-frontend.mjs to regenerate chunk-deposit.js.
//
// Emergency escape hatch (unrelated to this script): a #deposit-inline-template
// element in index.html overrides the embedded app at runtime via
// readTemplateHtmlFromHost() — usable for hotfixes without re-encoding.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_HTML = join(ROOT, "src-frontend", "deposit-app.html");
const BLOB_FILE = join(ROOT, "src-frontend", "deposit-app-blob.js");

const ASSIGN_RE = /window\.__EDAA_B64__ = `([A-Za-z0-9+/=]*)`/;

function renderBlobFile(encoded) {
  return (
    "/* GENERATED by scripts/build-edaa.mjs from src-frontend/deposit-app.html — DO NOT EDIT BY HAND. */\n" +
    "/* Loaded lazily as chunk-deposit.js; site-inline-app reads window.__EDAA_B64__ in loadEdAA. */\n" +
    "window.__EDAA_B64__ = `" + encoded + "`;\n"
  );
}

const mode = process.argv[2] || "build";

if (mode === "--extract") {
  const text = readFileSync(BLOB_FILE, "utf8");
  const m = text.match(ASSIGN_RE);
  if (!m) { console.error(`build-edaa: no __EDAA_B64__ assignment in ${BLOB_FILE}`); process.exit(1); }
  const bytes = Buffer.from(m[1], "base64");
  if (bytes.toString("base64") !== m[1]) {
    console.error("build-edaa: embedded base64 is not canonical — refusing to extract.");
    process.exit(1);
  }
  mkdirSync(dirname(SOURCE_HTML), { recursive: true });
  writeFileSync(SOURCE_HTML, bytes);
  console.log(`build-edaa: extracted ${bytes.length} bytes -> ${SOURCE_HTML}`);
  process.exit(0);
}

const encoded = readFileSync(SOURCE_HTML).toString("base64");
const next = renderBlobFile(encoded);
const current = existsSync(BLOB_FILE) ? readFileSync(BLOB_FILE, "utf8").replace(/\r\n/g, "\n") : "";

if (current === next) {
  console.log(`build-edaa: ${BLOB_FILE} — up to date.`);
} else if (mode === "--check") {
  console.error(`build-edaa: ${BLOB_FILE} — OUT OF DATE with ${SOURCE_HTML}.`);
  process.exit(1);
} else {
  writeFileSync(BLOB_FILE, next);
  console.log(`build-edaa: ${BLOB_FILE} — rewritten (${encoded.length} base64 chars).`);
}
